package com.example.uc_common_bean.greedao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.uc_common_bean.vo.SingerInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SINGER_INFO".
*/
public class SingerInfoDao extends AbstractDao<SingerInfo, Long> {

    public static final String TABLENAME = "SINGER_INFO";

    /**
     * Properties of entity SingerInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SingerCode = new Property(1, Integer.class, "singerCode", false, "SINGER_CODE");
        public final static Property SingerName = new Property(2, String.class, "singerName", false, "SINGER_NAME");
        public final static Property Picurl = new Property(3, String.class, "picurl", false, "PICURL");
        public final static Property CreateTime = new Property(4, String.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(5, String.class, "updateTime", false, "UPDATE_TIME");
    };


    public SingerInfoDao(DaoConfig config) {
        super(config);
    }
    
    public SingerInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SINGER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SINGER_CODE\" INTEGER," + // 1: singerCode
                "\"SINGER_NAME\" TEXT," + // 2: singerName
                "\"PICURL\" TEXT," + // 3: picurl
                "\"CREATE_TIME\" TEXT," + // 4: createTime
                "\"UPDATE_TIME\" TEXT);"); // 5: updateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SINGER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SingerInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer singerCode = entity.getSingerCode();
        if (singerCode != null) {
            stmt.bindLong(2, singerCode);
        }
 
        String singerName = entity.getSingerName();
        if (singerName != null) {
            stmt.bindString(3, singerName);
        }
 
        String picurl = entity.getPicurl();
        if (picurl != null) {
            stmt.bindString(4, picurl);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(5, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(6, updateTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SingerInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer singerCode = entity.getSingerCode();
        if (singerCode != null) {
            stmt.bindLong(2, singerCode);
        }
 
        String singerName = entity.getSingerName();
        if (singerName != null) {
            stmt.bindString(3, singerName);
        }
 
        String picurl = entity.getPicurl();
        if (picurl != null) {
            stmt.bindString(4, picurl);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(5, createTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(6, updateTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SingerInfo readEntity(Cursor cursor, int offset) {
        SingerInfo entity = new SingerInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // singerCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // singerName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // picurl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // createTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // updateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SingerInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSingerCode(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSingerName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPicurl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreateTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUpdateTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SingerInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SingerInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
